[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
# Set the maximum line length to 79.
line-length = 79
# Assume Python 3.10
target-version = "py310"

[tool.ruff.lint]
select = [
  "ALL",
]
extend-select = [
  "E501", # Add the `line-too-long` rule to the enforced rule set.
]
ignore = [
  "D", # Documentation
  "TCH002", # Move third-party import into a type-checking block
  "TCH003", # Move standard library import `datetime.datetime` into a type-checking block
  "RUF001", # String contains ambiguous `с` (CYRILLIC SMALL LETTER ES). Did you mean `c` (LATIN SMALL LETTER C)?
  "RUF002", # Docstring contains ambiguous `с` (CYRILLIC SMALL LETTER ES). Did you mean `c` (LATIN SMALL LETTER C)?
  "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
  "T201", # `print` found
  "BLE001", # Do not catch blind exception: `Exception`
  "DTZ005", # `datetime.datetime.now()` called without a `tz` argument
  "B006", # Do not use mutable data structures for argument defaults
  "PERF203", # `try`-`except` within a loop incurs performance overhead
  "PERF401", # Use a list comprehension to create a transformed list
  "FBT001", # Boolean-typed positional argument in function definition
  "N803", # Argument name `ticketCRUD` should be lowercase
  "N815", #  Variable `paidByBonuses` in class scope should not be mixedCase
  "E722", # Do not use bare `except
  "S113", # Probable use of `requests` call without timeout
  "ASYNC210", # Async functions should not call blocking HTTP methods
]
fixable = [
  "I001", # Import block is un-sorted or un-formatted
  "COM812", # Trailing comma missing
]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
